### ISSUE TITLE
Fix the SlicerSALT dashboard

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#341]
Fix the windows compilation of SlicerSALT, we are no longer getting windows packages.
It seems like the compilation works but the packages arent being uploaded 
FYI open.cdash.org/index.php?project=SlicerSALT

**Comment by bpaniagua** [comment]
Ping @jcfr @sjh26 
It seems like there has been a dashboard update and now mac and linux are also failing. 
Could one of you please look into this ASAP so we can push the SALT release this week?

**Comment by jcfr** [comment]
Windows build should be fixed after integrating the following:
* https://github.com/Kitware/SlicerSALT/pull/348

**Comment by jcfr** [comment]
The macOS build was fixed after updating the `CMAKE_OSX_DEPLOYMENT_TARGET` used in the dashboard script from `11.0` to `13.0`.

Following Kitware/SlicerSALT@7ed9adfec updating SlicerSALT to use the latest version of Slicer 5.9 from 2025-04-07. This is required because since Slicer/Slicer@ba3a9fdc04c introduced on 2024-10-12, the minimum required CMAKE_OSX_DEPLOYMENT_TARGET is 13.0.

Corresponding changes adapted from these commits:
* Slicer/DashboardScripts@b17fc43 ("computron: Update CMAKE_OSX_DEPLOYMENT_TARGET to 13.0", 2024-10-12)
* Slicer/DashboardScripts@a6c6eab ("computron: Update CMAKE_OSX_DEPLOYMENT_TARGET to 13.0 in stable scripts", 2025-01-23)

**Comment by bpaniagua** [comment]
@sjh26 is going to look into the mac build still failing 
https://open.cdash.org/builds/10360136/configure

**Comment by vicory** [comment]
Windows builds seem to succeed but they are still not being uploaded: https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5bd85a568d777f06b9402dad
